A = [ "python", 
     "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Angular",
        "Vue.js",
        "Responsive Design",
        "UI Design",
        "UX Design",
        "Bootstrap",
        "merhaba",
        "merhabalar",
        "selamlar",
        "selam",
        "merhabalar",
        "SASS/SCSS",
        "Webpack",
        "AJAX",
        "RESTful API",
        "fotograf",
        "görsel",
        "SELECT",
    "FROM",
    "WHERE",
    "JOIN",
    "INNER JOIN",
    "OUTER JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "INSERT INTO",
    "UPDATE",
    "DELETE",
    "CREATE TABLE",
    "ALTER TABLE",
    "PRIMARY KEY",
    "FOREIGN KEY",
    "INDEX",
    "TRIGGER",
        "fotoğraf",
        "ekran",
        "screenshot",
        "JSON",
        "DOM",
        "Frontend Framework",
        "Cross-Browser Compatibility",
        "Web Accessibility",
        "Single Page Application (SPA)",
        "Vector",
        "Matrix",
        "Scalar",
        "Linear Transformation",
        "Eigenvalue",
        "Eigenvector",
        "Determinant",
        "Transpose",
        "Orthogonal",
        "Rank",
        "Span",
        "Basis",
        "Inner Product",
        "Singular Value Decomposition (SVD)",
        "Matrix Inversion",
        "Least Squares",
        "Linear Independence",
        "Cross Product",
        "Dot Product",
        "Row Echelon Form",
        "Model-View-Controller (MVC)",
        "ORM (Object-Relational Mapping)",
        "Django Models",
        "Django Views",
        "Django Templates",
        "Django Forms",
        "Django Admin",
        "QuerySet",
        "Middleware",
        "Django Rest Framework",
        "Django Migrations",
        "Django URL Patterns",
        "Django Signals",
        "Django Static Files",
        "Django Middleware",
        "Django Database API",
        "Django Authentication",
        "Django Middleware",
        "Django Middleware",
        "Django Middleware",
        "Git",
        "GitHub",
        "Repository",
        "Branch",
        "Commit",
        "Merge",
        "Pull Request",
        "Fork",
        "Clone",
        "Remote",
        "Origin",
        "Upstream",
        "Gitignore",
        "Version Control System",
        "Master Branch",
        "Conflict Resolution",
        "Git Workflow",
        "GitHub Actions",
        "Issue",
        "Wiki",
        "Git Hooks",
        "Submodule",
        "Laravel",
        "SaaS (Software as a Service)",
        "Multi-Tenancy",
        "Subscription Billing",
        "Tenant",
        "Billing Cycle",
        "User Authentication",
        "Laravel Blade Templates",
        "Laravel Eloquent ORM",
        "Laravel Migrations",
        "Laravel Middleware",
        "Laravel Artisan",
        "Laravel Nova",
        "Laravel Passport",
        "Laravel Cashier",
        "Laravel Vapor",
        "SaaS Metrics",
        "Trial Period",
        "Role-Based Access Control (RBAC)",
        "Invoice Generation",
        "Payment Gateway Integration",
        "REST (Representational State Transfer)",
        "API (Application Programming Interface)",
        "Endpoint",
        "HTTP Methods (GET, POST, PUT, DELETE)",
        "JSON (JavaScript Object Notation)",
        "XML (eXtensible Markup Language)",
        "Authentication Token",
        "Request",
        "Response",
        "Status Code",
        "Rate Limiting",
        "Pagination",
        "Versioning",
        "versiyon",
        "kontrol",
        "HATEOAS (Hypermedia As The Engine Of Application State)",
        "Webhooks",
        "Cross-Origin Resource Sharing (CORS)",
        "GraphQL",
        "SOAP (Simple Object Access Protocol)",
        "Stateless",
        "Stateful",
     "generative",
     "prompt",
     "opeanai",
     "css",
     "hata",
     "hmtl",
     "okut",
     "işlem",
     "/",
     "( )",
     "coef",
     "corr",
     "korelason",
     "validasyon",
     "metric",
     "metrik",
     "csv",
     "xml",
     "excel",
     "csv",
     "kurulum",
     "zaman serileri",
     "lag",
    "üretken",
    "accuracy",
"veri",
"anlamadım",
"anlayamadım",
    "analiz",
    "oran",
    "kategorik",
    "sayısal",
    "değişken",
    "frekans",
    "dağılım",
    "varyans",
    "ki-kare",
    "ki kare",
    "anova",
    "test",
    "standart sapma",
    "ortalama",
    "medyan",
    "mod",
    "kesikli",
    "sürekli",
    "olabilirlik",
    "popülasyon",
    "örneklem",
    "hipotez",
    "p-değeri",
    "istatistiksel anlamlılık",
    "anova",
    "regresyon",
    "korelasyon",
    "chi-kare",
    "normal dağılım",
    "kesikli olasılık dağılımı",
    "binom dağılım",
    "poisson dağılım",
    "standart normal dağılım",
    "kesikli uniform dağılım",
    "kesikli bernoulli dağılım",
    "çapraz tablo",
    "kesikli veri",
    "kesikli değişken",
    "kesikli rastgele değişken",
    "olabilirlik dağılımı",
    "varsayım kontrolü",
    "istatistiksel test",
    "regresyon analizi",
    "belirginlik düzeyi",
    "varyans analizi",
    "standart hata",
    "fitting",
    "target",
        "F1",
        "skor",
        "xgboost",
        "lightgbm",
        "model",
        "yardımcı",
        "error",
        "hata",
        "kod",
        "analiz",
        "istatistik",
        "df",
        "plot",
        "show",
        "np",
        "pd",
        "import",
        "virtual",
        "orman",
        "random",
        "pd.",
        "np.",
        "path",
        "değişken",
        "dağılım",
        "betimsel",
    "if",
    "else",
    "for",
    "while",
    "fonksiyon",
    "sınıf",
    "liste",
    "demet",
    "sözlük",
    "koşul",
    "döngü",
    "indentasyon",
    "modül",
    "kütüphane",
    "try",
    "except",
    "import",
    "print",
    "input",
    "return",
    "append",
    "split",
    "join",
    "lambda",
    "map",
    "filter",
    "global",
    "local",
    "sort",
    "len",
    "enumerate",
    "open",
    "read",
    "write",
    "with",
    "yield",
    "self",
    "True",
    "False",
    "Veri Bilimi",
    "Python",
    "Docker",
    "Veri Analizi",
    "Makine Öğrenimi",
    "Veritabanı",
    "Yapay Zeka",
    "Veri Madenciliği",
    "Pandas",
    "Numpy",
    "Scikit-learn",
    "Jupyter",
    "Veri Görselleştirme",
    "Veri Tabanı Yönetimi",
    "Veri Saklama",
    "CSV",
    "Veri Seti",
    "Veri Temizleme",
    "Veri Modelleme",
    "Veri İşleme",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "NLP (Doğal Dil İşleme)",
    "Veri Keşfi",
    "Big Data",
    "Hadoop",
    "Spark",
    "Veri Yönetimi",
    "Data Engineering",
    "Veri Sızdırmazlık",
    "Data Science Pipeline",
    "Dockerfile",
    "Containerization",
    "Docker Hub",
    "Docker Compose",
    "Docker Swarm",
    "Konteyner",
    "Orkestrasyon",
    "Docker İmage",
    "Docker Volume",
    "Kubernetes",
    "K8s",
    "Pod",
    "Docker Compose",
    "Kubelet",
    "Minikube",
    "Kubeconfig",
    "YAML Dosyası",
    "Kube Proxy",
    "Docker Compose",
    "Docker Registry",
    "Konteyner Ağı",
    "Kubernetes Hizmeti",
    "Kubeconfig Dosyası",
    "Kube Controller Manager",
    "Kube Scheduler",
    "Kube API Sunucusu",
    "Kubelet",
    "Büyük Veri",
    "Veri Depolama",
    "Veri İşleme",
    "Veri Analitiği",
    "Data Lake",
    "Data Warehouse",
    "ETL (Extract, Transform, Load)",
    "SQL",
    "NoSQL",
    "Veri Tabanı Yönetimi",
    "DBMS (Veritabanı Yönetim Sistemi)",
    "SQL Server",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Cassandra",
    "Veri Tabanı Tasarımı",
    "ACID",
    "CAP Teoremi",
    "Veri Modelleme",
    "SQL Sorguları",
    "Database Index",
    "Stored Procedure",
    "Veri Yedekleme",
    "Veri Güvenliği",
    "Veri Analizi Aracı",
    "Data Mining",
    "Data Cleansing",
    "Data Exploration",
    "Data Visualization",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Data Dashboard",
    "Data Insights",
    "Machine Learning Algorithms",
    "Supervised Learning",
    "Unsupervised Learning",
    "Reinforcement Learning",
    "Classification",
    "Regression",
    "Clustering",
    "Dimensionality Reduction",
    "Ensemble Learning",
    "Deep Learning",
    "Neural Networks",
    "Convolutional Neural Networks (CNN)",
    "Recurrent Neural Networks (RNN)",
    "Natural Language Processing (NLP)",
    "Sentiment Analysis",
    "Text Mining",
    "Topic Modeling",
    "Word Embeddings",
    "Tokenization",
    "Data Engineering",
    "Data Pipeline",
    "ETL (Extract, Transform, Load)",
    "Data Integration",
    "Data Warehousing",
    "Big Data Technologies",
    "Hadoop",
    "MapReduce",
    "Hive",
    "Spark",
    "Scala",
    "Data Streaming",
    "Apache Kafka",
    "Stream Processing",
    "Real-Time Analytics",
    "Distributed Systems",
    "Containerization",
    "Docker Image",
    "Kubernetes Orchestration",
    "Microservices",
    "DevOps",
    "CI/CD",
    "Version Control",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Continuous Integration",
    "Continuous Deployment",
    "Infrastructure as Code (IaC)",
    "Container Orchestration",
    "Docker Swarm",
    "Kubernetes",
    "Monitoring and Logging",
    "ELK Stack",
    "Prometheus",
    "Grafana",
    "Application Deployment",
    "Load Balancing",
    "Scalability",
    "Service Discovery",
    "Container Registry",
    "Docker Hub",
    "Docker Compose",
    "K8s Dashboard",
    "Kubeconfig",
    "YAML Configuration",
    "Cloud Computing",
    "Amazon Web Services (AWS)",
    "Amazon EC2",
    "Amazon S3",
    "Amazon RDS",
    "Google Cloud Platform (GCP)",
    "Google Compute Engine",
    "Google Kubernetes Engine (GKE)",
    "Microsoft Azure",
    "Azure Virtual Machines",
    "Azure Kubernetes Service (AKS)",
    "Serverless Computing",
    "AWS Lambda",
    "Google Cloud Functions",
    "Azure Functions",
    "Data Security",
    "Encryption",
    "Access Control",
    "Data Privacy",
    "Compliance",
    "Cybersecurity",
    "Data Breach",
    "Data Masking",
    "Data Encryption",
    "SSL/TLS",
    "OAuth",
    "Multi-Factor Authentication",
    "Penetration Testing",
    "Cyber Threat Intelligence",
    "Incident Response",
    "Security Operations Center (SOC)",
    "Ethical Hacking",
    "ISO 27001",
    "HIPAA",
    "GDPR",
    "Data Analytics",
    "Statistical Analysis",
    "Descriptive Statistics",
    "Inferential Statistics",
    "A/B Testing",
    "Hypothesis Testing",
    "Data-driven Decision Making",
    "Business Intelligence",
    "Data Reporting",
    "Dashboard Design",
    "Data Science Tools",
    "Jupyter Notebook",
    "Python Libraries",
    "Pandas",
    "Numpy",
    "Scipy",
    "Scikit-learn",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "NLTK",
    "Spacy",
    "Beautiful Soup",
    "Flask",
    "Django",
    "SQLAlchemy",
    "Data Visualization Tools",
    "Tableau",
    "Power BI",
    "QlikView",
    "D3.js",
    "Data Engineering Tools",
    "Apache NiFi",
    "Apache Airflow",
    "Talend",
    "Apache Beam",
    "Database Management Systems (DBMS)",
    "Relational Database Management System (RDBMS)",
    "NoSQL Database",
    "Document-oriented Database",
    "Key-Value Store",
    "Columnar Database",
    "Graph Database",
    "In-memory Database",
    "Time Series Database",
    "Database Indexing",
    "Query Optimization",
    "Database Replication",
    "Database Sharding",
    "Database Backup and Recovery",
    "Database Security",
    "SQL Injection",
    "Data Warehouse Design",
    "Star Schema",
    "Snowflake Schema",
    "ETL Process",
    "Data Governance",
    "Data Catalog",
    "Data Quality",
    "Master Data Management (MDM)",
    "Data Lifecycle Management",
    "Data Lake Architecture",
    "Data Warehouse vs. Data Lake",
    "Data Modeling Techniques",
    "Entity-Relationship Diagram (ERD)",
    "Dimensional Modeling",
    "Normalized vs. Denormalized Data",
    "Data Warehouse ETL Process",
    "Data Mining Algorithms",
    "Association Rules",
    "Cluster Analysis",
    "Decision Trees",
    "Random Forest",
    "Support Vector Machines (SVM)",
    "Naive Bayes",
    "k-Means Clustering",
    "Principal Component Analysis (PCA)",
    "Collaborative Filtering",
    "Recommender Systems",
    "Deep Learning Frameworks",
    "Convolutional Neural Network (CNN)",
    "Recurrent Neural Network (RNN)",
    "Long Short-Term Memory (LSTM)",
    "Generative Adversarial Networks (GAN)",
    "Natural Language Processing (NLP) Libraries",
    "Tokenization",
    "Stemming",
    "Lemmatization",
    "Stop Words",
    "Named Entity Recognition (NER)",
    "Sentiment Analysis",
    "Text Classification",
    "Word Embeddings",
    "BERT",
    "GPT-3",
    "Word2Vec",
    "Data Preprocessing",
    "Data Cleaning",
    "Data Transformation",
    "Feature Engineering",
    "Scaling",
    "Imputation",
    "Outlier Detection",
    "Dimensionality Reduction",
    "Feature Selection",
    "Cross-Validation",
    "Model Evaluation Metrics",
    "Accuracy",
    "Precision",
    "Recall",
    "F1-Score",
    "ROC Curve",
    "Confusion Matrix",
    "Bias and Fairness in Machine Learning",
    "Explainable AI (XAI)",
    "Machine Learning Model Deployment",
    "RESTful API",
    "Docker Containerization",
    "Kubernetes Orchestration",
    "Model Serving",
    "Monitoring Machine Learning Models",
    "Data Labeling",
    "Data Annotation",
    "Active Learning",
    "Transfer Learning",
    "AutoML",
    "Hyperparameter Tuning",
    "AI Ethics",
    "Responsible AI",
    "Bias Mitigation",
    "Fairness Auditing",
    "Privacy-Preserving AI",
    "crm",
    "segmentasyon",
    "git",
    "def",
    "anla" ]
    